In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [2]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Wallasey,GB,2022-05-01 21:20:41,53.4232,-3.0650,54.81,86,75,6.91
1,1,New Norfolk,AU,2022-05-01 21:20:42,-42.7826,147.0587,58.87,84,87,3.00
2,2,Kulhudhuffushi,MV,2022-05-01 21:20:42,6.6221,73.0700,84.70,75,79,15.68
3,3,Hermanus,ZA,2022-05-01 21:20:43,-34.4187,19.2345,57.79,90,35,10.25
4,4,Los Llanos De Aridane,ES,2022-05-01 21:20:43,28.6585,-17.9182,64.15,85,0,10.36

In [3]:
# Get the data types.
city_data_df.dtypes

City_ID         int64
City           object
Country        object
Date           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

In [4]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [5]:
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))

In [6]:
# Heatmap of temperature.

# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]

# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]

# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=temps, dissipating=False, max_intensity=300, point_radius=4)

# Add the heatmap layer.
fig.add_layer(heat_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [7]:
# Heatmap of percent humidity.

# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]

# Get the maximum temperature.
humidity = city_data_df["Humidity"]

# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

# Add the heatmap layer.
fig.add_layer(heat_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [8]:
# Heatmap of percent cloudiness.

# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]

# Get the maximum temperature.
clouds = city_data_df["Cloudiness"]

# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

# Add the heatmap layer.
fig.add_layer(heat_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [9]:
# Heatmap of temperature.

# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]

# Get the maximum temperature.
wind = city_data_df["Wind Speed"]

# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

# Add the heatmap layer.
fig.add_layer(heat_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [10]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [11]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
2,2,Kulhudhuffushi,MV,2022-05-01 21:20:42,6.6221,73.0700,84.70,75,79,15.68
5,5,Kapaa,US,2022-05-01 21:20:44,22.0752,-159.3190,80.58,76,40,18.41
11,11,Puerto Ayora,EC,2022-05-01 21:18:23,-0.7393,-90.3518,78.76,80,65,8.25
14,14,Tecoanapa,MX,2022-05-01 21:20:48,16.5167,-98.7500,86.74,49,97,9.69
18,18,Veraval,IN,2022-05-01 21:20:49,20.9000,70.3667,82.38,90,0,11.70
20,20,Arraial Do Cabo,BR,2022-05-01 21:20:50,-22.9661,-42.0278,76.86,88,0,8.05
26,26,Tarauaca,BR,2022-05-01 21:20:54,-8.1614,-70.7656,80.80,75,99,2.55
27,27,Vaini,TO,2022-05-01 21:20:55,-21.2000,-175.2000,80.76,89,75,11.50
31,31,Atuona,PF,2022-05-01 21:20:57,-9.8000,-139.0333,78.53,81,100,13.29
35,35,Dicabisagan,PH,2022-05-01 21:21:00,17.0818,122.4157,77.31,86,86,2.35

In [12]:
preferred_cities_df.count()

City_ID       161
City          161
Country       161
Date          161
Lat           161
Lng           161
Max Temp      161
Humidity      161
Cloudiness    161
Wind Speed    161
dtype: int64

In [13]:
preferred_cities_df.isnull().sum()

City_ID       0
City          0
Country       0
Date          0
Lat           0
Lng           0
Max Temp      0
Humidity      0
Cloudiness    0
Wind Speed    0
dtype: int64

In [14]:
preferred_cities_df.notnull().sum()

City_ID       161
City          161
Country       161
Date          161
Lat           161
Lng           161
Max Temp      161
Humidity      161
Cloudiness    161
Wind Speed    161
dtype: int64

In [19]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(50)

                 City Country  Max Temp      Lat       Lng Hotel Name
2      Kulhudhuffushi      MV     84.70   6.6221   73.0700
5               Kapaa      US     80.58  22.0752 -159.3190
11       Puerto Ayora      EC     78.76  -0.7393  -90.3518
14          Tecoanapa      MX     86.74  16.5167  -98.7500
18            Veraval      IN     82.38  20.9000   70.3667
20    Arraial Do Cabo      BR     76.86 -22.9661  -42.0278
26           Tarauaca      BR     80.80  -8.1614  -70.7656
27              Vaini      TO     80.76 -21.2000 -175.2000
31             Atuona      PF     78.53  -9.8000 -139.0333
35        Dicabisagan      PH     77.31  17.0818  122.4157
36            Katiola      CI     81.90   8.1333   -5.1000
37             Trairi      BR     79.83  -3.2778  -39.2689
41            Rikitea      PF     76.30 -23.1203 -134.9692
46              Mecca      SA     83.37  21.4267   39.8261
50       Port Hedland      AU     75.25 -20.3167  118.5667
52            Sedhiou      SN     85.48  12.7081  -15.5569
57            Kahului      US     78.82  20.8947 -156.4700
64         Butaritari      KI     81.50   3.0707  172.7902
66            Nioaque      BR     84.04 -21.1353  -55.8300
68            Vayalar      IN     80.11   9.7000   76.3333
69               Poum      NC     77.67 -20.2333  164.0167
70            Salalah      OM     86.09  17.0151   54.0924
71           Rockport      US     87.82  28.0206  -97.0544
72            Samarai      PG     80.74 -10.6167  150.6667
73          Hithadhoo      MV     85.60  -0.6000   73.0833
76    Barra Do Garcas      BR     79.03 -15.8900  -52.2567
77          Sinnamary      GF     79.83   5.3833  -52.9500
79           Karratha      AU     80.06 -20.7377  116.8463
82            Estelle      US     86.00  29.8458  -90.1067
83       Lake Jackson      US     88.03  29.0339  -95.4344
85            Lucknow      IN     82.38  26.8500   80.9167
87           Acajutla      SV     86.43  13.5928  -89.8275
102     San Policarpo      PH     80.24  12.1791  125.5072
109            Dingle      PH     76.01  10.9995  122.6711
117           Isangel      VU     84.31 -19.5500  169.2667
125  Kuala Terengganu      MY     78.75   5.3302  103.1408
126            Nicoya      CR     88.54  10.1483  -85.4520
127          Marshall      US     82.38  34.3834  -86.3333
131            Jiwani      PK     84.20  25.0500   61.7417
133        Vila Velha      BR     82.35 -20.3297  -40.2925
135          Lorengau      PG     80.64  -2.0226  147.2712
143           Mayumba      GA     78.53  -3.4320   10.6554
144             Kroya      ID     77.25  -7.6331  109.2461
145            Loreto      MX     82.99  22.2667 -101.9667
158           Fayaoue      NC     77.95 -20.6500  166.5333
160             Anito      PH     78.10  12.4497  125.2886
161        Port Blair      IN     82.72  11.6667   92.7500
162            Namibe      AO     75.27 -15.1961   12.1522
165        Georgetown      MY     82.33   5.4112  100.3354
167             Ambon      ID     77.14  -3.6954  128.1814

In [20]:
# Set parameters to search for a hotel.
params = {
    "radius": 10000,
    "type": "lodging",
    "key": g_key
}

In [21]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][50]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [22]:
# Add a heatmap of temperature for the vacation spots.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [23]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [25]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

In [26]:
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [27]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))